version: 0.1
log:
  level: info
  fields:
    service: registry
storage:
  filesystem:
    rootdirectory: /var/lib/registry
  delete:
    enabled: true
  cache:
    blobdescriptor: inmemory
  maintenance:
    uploadpurging:
      enabled: true
      age: 168h
      interval: 24h
      dryrun: false
http:
  addr: :5000
  relativeurls: true
compatibility:
  schema1:
    enabled: true
health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3
