{
  config,
  pkgs,
  ...
}: {
  imports = [
    ../../modules/common.nix
    ../../modules/disko-config.nix
    ../../modules/tailscale.nix
    ../../modules/step-ca-trust.nix
    ../../modules/podman.nix
    ../../modules/moshi-hook-user.nix
    ../../modules/coding-harness.nix
    ../../modules/herdr.nix
    ../../modules/claude-permissions.nix
    ../../modules/claude-settings-verify.nix
    ../../modules/attic-cache.nix
    ../../modules/forgejo-cli.nix
  ];

  home-manager.users.amadeus.imports = [../../modules/jj.nix];

  networking.hostName = "homelab-development";

  # This VM has TWO disks — the 256 GB OS disk (scsi0) and a 4 MB cloud-init
  # drive on the ATA bus — so /dev/sdX enumeration is not stable and disko could
  # target the cloud-init disk inside the nixos-anywhere installer. Override
  # modules/disko-config.nix's lib.mkDefault "/dev/sda" with the stable by-id
  # path. See AGENTS.md §6 "Multi-Disk VMs: Pin Disko Devices by /dev/disk/by-id".
  disko.devices.disk.main.device = "/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_drive-scsi0";

  # Static IP configuration
  networking.interfaces.ens18 = {
    useDHCP = false;
    ipv4.addresses = [
      {
        address = "192.168.2.184";
        prefixLength = 24;
      }
    ];
  };
  networking.defaultGateway = "192.168.2.1";

  # Node exporter for Prometheus monitoring
  services.prometheus.exporters.node = {
    enable = true;
    enabledCollectors = ["systemd" "processes"];
  };

  # Compressed RAM swap, as the first line of defence under memory pressure.
  #
  # The only other swap here is the 4 GB btrfs swapfile from
  # modules/disko-config.nix, which lives on the root disk — i.e. on the 2-HDD
  # zfs_pool that backs every VM in the cluster (~78 IOPS total). When several
  # agent sessions realise a devShell at once this host exhausted all 4 GB of
  # it, and every page fault then competed for those IOPS, so a busy
  # `development` degraded unrelated VMs. zram absorbs the same spike in RAM at
  # zero IO cost.
  #
  # NixOS gives zram priority 5 against the swapfile's default, so the kernel
  # fills zram first and only reaches for the disk once zram is full — which
  # keeps the HDD path as a genuine last resort rather than the default.
  zramSwap = {
    enable = true;
    algorithm = "zstd";
    memoryPercent = 25;
  };

  # Podman (+ Docker compat, container DNS) comes from ../../modules/podman.nix

  networking.firewall = {
    enable = true;
    # podman+ = every podman bridge (podman0 plus any per-experiment network).
    # Without trusting them the host firewall drops container -> aardvark-dns
    # traffic, so containers can't resolve each other. See harbor's podman1 note.
    trustedInterfaces = ["tailscale0" "podman+"];
    allowedTCPPorts = [
      22 # SSH
      9100 # Node exporter
    ];
  };

  # Forgejo access for Claude Code, which runs interactively as amadeus and
  # pushes/creates repos as the `developmentbot` account. The keypair itself is
  # a plain local credential at ~/.ssh/id_ed25519 (generated once on the host,
  # public half registered on the account) — deliberately NOT an agenix secret:
  # the repos live on Forgejo, so a wiped VM just registers a fresh key.
  #
  # NB: the SSH user is "forgejo" (the built-in Forgejo SSH server's user), NOT
  # "git" — connecting as git@ is silently rejected. See AGENTS.md §7.
  # Colmena deploy key. This host runs unattended agent sessions as amadeus, so
  # a plain key here would mean any agent can deploy the fleet. The private key
  # is therefore **passphrase-protected** and generated by hand on the host —
  # never in this repo, never an agenix secret (agenix would hand the plaintext
  # to the same user we are trying to gate):
  #
  #   ssh-keygen -t ed25519 -f ~/.ssh/id_colmena -C "amadeus@development-colmena"
  #
  # `IdentityAgent none` is the load-bearing line. Without it the passphrase
  # buys nothing the moment the key is `ssh-add`ed: any process running as
  # amadeus — every agent session included — can use an unlocked key through
  # $SSH_AUTH_SOCK without ever seeing the passphrase. With it, ssh ignores the
  # agent for these hosts and prompts on the controlling TTY, so a
  # non-interactive `colmena apply` fails closed instead of succeeding silently.
  # The cost is one passphrase prompt per target host per deploy; that prompt is
  # the consent gate, so do not "fix" it with `ssh-add`.
  #
  # Ordering and negation both matter. `IdentityFile` *accumulates* across
  # matching blocks rather than first-one-wins, so without the `!forgejo.*`
  # negations every git push to Forgejo would also offer id_colmena and prompt
  # for its passphrase. Keep the Forgejo block first and both negations in place.
  #
  # Every pattern is listed for BOTH zones because hosts/dns/configuration.nix
  # serves homelab.internal as a full parallel mirror of every homelab.local A
  # record, and .internal is the canonical name (it is an ICANN-reserved suffix,
  # so macOS/iOS resolve it over Tailscale split DNS where .local does not).
  # A block matching only .local means `ssh <host>.homelab.internal` matches
  # nothing here and silently falls through to ssh's defaults — no pinned
  # identity, no `IdentityAgent none`, so the consent gate above does not apply
  # and the agent socket is back in play. Add new patterns in pairs.
  #
  # `!*.ts.net` exists because `homelab-*` is greedier than it looks: the git
  # remote here is ssh://forgejo@homelab-forgejo.dropbear-butterfly.ts.net:2222,
  # which `homelab-*` matches. That handed Forgejo an IdentitiesOnly list
  # containing just id_colmena and no agent fallback, so `git pull` died with
  # `Permission denied (publickey)` — and silently, with no passphrase prompt,
  # because ssh offers the *public* key first and never needs to decrypt one the
  # server has already rejected. Colmena's Tailscale targets are the bare names
  # (`homelab-forgejo`, from hostAddrs in flake.nix), which `!*.ts.net` leaves
  # matching, so deploys over DEPLOY_NET=tailscale still get the key.
  #
  # `StrictHostKeyChecking accept-new` because this host starts with an empty
  # known_hosts: without it the first colmena run dies with "Host key
  # verification failed" on every target, before the passphrase prompt is ever
  # reached. accept-new is trust-on-first-use — it still refuses a host key that
  # *changes* later, which is the case that matters. Note a reinstalled host
  # gets a new key and will then be refused until its known_hosts line is
  # dropped; that is the same re-provisioning footgun that breaks agenix.
  programs.ssh.extraConfig = ''
    Host forgejo.homelab.local forgejo.homelab.internal
      Port 2222
      User forgejo
      IdentityFile ~/.ssh/id_ed25519
      IdentitiesOnly yes
      StrictHostKeyChecking accept-new

    Host *.homelab.local *.homelab.internal homelab-* 192.168.2.* !forgejo.homelab.local !forgejo.homelab.internal !*.ts.net
      User amadeus
      # TEMPORARY (revert me): passphraseless deploy key so colmena can push
      # non-interactively. This DEFEATS the consent gate documented above — any
      # agent session as amadeus can now deploy the fleet. Swap back to
      # `~/.ssh/id_colmena` and delete `~/.ssh/id_colmena_deploy` once the whole
      # fleet has been re-deployed with the current authorized_keys.
      IdentityFile ~/.ssh/id_colmena_deploy
      IdentitiesOnly yes
      IdentityAgent none
      StrictHostKeyChecking accept-new

    # Colmena deploys of the separate ventara fleet (nixos-ventara-ai repo),
    # driven from here with `DEPLOY_NET=tailscale just deploy-vm01`. That makes
    # colmena's target the bare MagicDNS name `ventara-vm01` (the `local`
    # 10.0.10.x address lives behind vidar-01's NAT and is unreachable from
    # here without a ProxyJump). MagicDNS resolves it from this host
    # (ventara-vm01 -> 100.x on the shared tailnet), so no HostName pin is
    # needed. The name matches NONE of the homelab patterns above (it is not
    # `homelab-*`/`*.homelab.local`/`192.168.2.*`), so without this block ssh
    # falls back to the broken managed agent and prompts to unlock the key.
    # Same deploy key + `IdentityAgent none` as the homelab block; ventara's
    # modules/common.nix authorizes this key's pubkey (amadeus@development-colmena).
    Host ventara-vm01 ventara-vm01.dropbear-butterfly.ts.net
      User amadeus
      IdentityFile ~/.ssh/id_colmena_deploy
      IdentitiesOnly yes
      IdentityAgent none
      StrictHostKeyChecking accept-new
  '';

  # Commit identity, so a reinstall doesn't leave git prompting for one.
  # Matches the bot account the SSH key authenticates as.
  programs.git = {
    enable = true;
    config = {
      user.name = "developmentbot";
      user.email = "developmentbot@homelab.local";
      init.defaultBranch = "main";
      pull.rebase = true;
    };
  };

  # Per-project dev shells, entered automatically. Every repo under ~/code ships
  # a flake.nix whose shellHook runs `lefthook install`, so without direnv the
  # git hooks are never installed and tools like keep-sorted/cog/just aren't on
  # PATH — commits then fail with "command not found". nix-direnv (enabled by
  # default here) adds the eval cache and GC roots that make `use flake` usable.
  programs.direnv = {
    enable = true;
    silent = true;
  };

  # Moshi pairing token (plain raw text, NOT KEY=value — read directly by
  # modules/moshi-hook-user.nix's pair script). Owned by amadeus so
  # moshi-hook-setup (User=amadeus) can read it.
  age.secrets.moshi-device-id = {
    file = ../../secrets/moshi-device-id.age;
    owner = "amadeus";
    mode = "0400";
  };

  # Axon MCP gateway bearer token (file contains AXON_GATEWAY_TOKEN=...).
  # Owned by amadeus: modules/coding-harness.nix sources it directly into
  # every interactive login shell (environment.interactiveShellInit) so
  # Claude Code / opencode can expand it from their MCP config at runtime.
  age.secrets.axon-gateway-env = {
    file = ../../secrets/axon-gateway-env.age;
    owner = "amadeus";
    mode = "0400";
  };

  # opencode-zen provider key (env-file: OPENCODE_ZEN_API_KEY=...). Declared
  # under the generic `opencode-zen-key` attribute that modules/coding-harness.nix
  # looks for, while the file itself is per-host — every consumer gets its own
  # key so a leak is contained and revocation is per-host. hermes keeps its own
  # separate hermes-opencode-zen-key.age.
  age.secrets.opencode-zen-key = {
    file = ../../secrets/development-opencode-zen-key.age;
    owner = "amadeus";
    mode = "0400";
  };

  # Attic push token + login + auto-push-on-activation now come from
  # modules/attic-push.nix, pulled in fleet-wide via cominFor (modules/comin.nix)
  # since this host is comin-managed. Used to be defined here inline; moved out
  # so every comin host gets the same push setup instead of just this one.

  # Forgejo API token for the `developmentbot` account (env-file:
  # FORGEJO_TOKEN=...). Needed ONLY to create repos over the REST API — git
  # itself authenticates with the ~/.ssh/id_ed25519 key registered on that
  # account, so losing this token costs nothing but a re-mint. Owned by amadeus
  # because Claude Code runs interactively as amadeus.
  age.secrets.development-forgejo-token = {
    file = ../../secrets/development-forgejo-token.age;
    owner = "amadeus";
    mode = "0400";
  };

  # Export FORGEJO_TOKEN into every interactive login shell. `interactiveShellInit`
  # is types.lines, so this MERGES with modules/coding-harness.nix's identical
  # block for axon-gateway-env rather than conflicting. Gated on readability, so
  # it's a silent no-op for any user other than the secret's owner.
  environment.interactiveShellInit = ''
    if [ -r "${config.age.secrets.development-forgejo-token.path}" ]; then
      set -a
      . "${config.age.secrets.development-forgejo-token.path}"
      set +a
    fi
  '';

  environment.shellAliases = {
    op = "opencode";
    cl = "claude";
  };

  # Development tools for experiments
  environment.systemPackages = with pkgs; [
    # keep-sorted start
    bat
    btop
    # bun + nodejs: opencode's global plugins (~/.config/opencode/plugins/
    # moshi-hooks.ts, herdr-agent-state.js) import @opencode-ai/plugin and
    # bun:sqlite, and opencode bootstraps their node_modules on first run.
    bun
    claude-code
    curl
    delta
    eza
    fd
    fzf
    # git comes from programs.git above (which also writes /etc/gitconfig)
    htop
    httpie
    jq
    lazygit
    neovim
    nodejs
    opencode
    podman-compose
    ripgrep
    tmux
    wget
    yq
    # keep-sorted end
  ];
}
