set dotenv-load

default:
    just --choose

clear:
  clear

shell:
  nix develop . --command zsh

fmt: clear
  tofu  fmt

validate: fmt
  tofu  validate

plan: fmt
  tofu plan

apply: validate plan
  tofu  apply

destroy: clear
  tofu destroy
