let
  # keep-sorted start
  amadeus = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHv1USrKf6yIjg8dZolm37xGysGfj18ol1KUKqsVuQHa amadeus@wotan";
  amadeusMacbook = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIH/HCRJuzlIbgcWk68ehApZl6kN+7PnKIgYSLRZ5IjzQ amadeus@Amadeuss-MacBook-Pro.local";
  amadeusMacbookAge = "age1uslcewyhmagupmfg4nf9tc6alj8edapzexnjvuhrkkmwd3wmy4nqpmel7t"; # ~/.config/age/keys.txt on the MacBook
  amadeusWotanAge = "age108er4kc0200y2at2fauw08t77u506nah2qxqlkxn8hq5c58e037qx226tw"; # ~/.config/age/keys.txt on wotan
  hostCa = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIF8i5IfaebQeFqqmZnIKrFNFNfnEvCIsnRamVnO/YyWx root@homelab-ca";
  hostCache = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIK3zPdNuF7/Xwxxhs6isTeG1K3fodO+lbQdWcfZUid4k root@homelab-cache";
  hostContainers = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKHmDtkEG9WNd6bvbEM3+HhdfnSu29o5bYskujiM6VdF root@homelab-containers";
  hostDatabase = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMOzKKGEVZy4w556Y3n1KQQrWVJUxU7XfHULii9W1qTr amadeus@homelab-database";
  hostDevelopment = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINpHEt4OMS5HwaSunrmU68JzkM2gu1MVcXqKZSQAhMe8 root@homelab-development";
  hostDns = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIH+lXepG2LjFNYvqGZtpWlsajmQNEaMx1y+f2rn6L7/2 root@homelab-dns"; # regenerated by the 2026-09-09 XFS reinstall
  hostFleet = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICLI6UX6dd+pyXOd8TIQ3NY3Ryff2gCH4oTd1YWjvzm8 root@homelab-fleet";
  hostForgejo = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIByBR3nP+bKlGcC6p62Pg5w1cPZsdh1FHBE6RUfbchDo root@homelab-forgejo";
  hostHarbor = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBJmT6FxRSlang9smAuBoq1QhYGtQ4adP4kK1lkLn8Ip root@homelab-harbor";
  hostHermes = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINT6kV2OW2mlBGmK/mA7k1FQAHHDFYN5NbW4Weo379rK root@homelab-hermes"; # minted by the 2026-09-24 rebuild install
  hostJellyfin = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDjBjNv4pvr08UdR2QL72Re3B22cUV+3DQvR2oG3/nsA root@homelab-jellyfin";
  hostMcp = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGkfmvav5dWx4dAbDHcJSuKG32GSmdVdOK+uQ1xjCtse root@homelab-mcp";
  hostOtel = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGz4mCD5XyFkwVaSzzWHhral8WqMGo01nKZM3gAX2vzP amadeus@homelab-otel";
  hostUnifi = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIG1dva0wW3yY7pu0bT2HafVcn08BZMjzTwEh3CGcdfb8 root@homelab-unifi";
  hostWoodpecker = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIACJjy5GtvoeSP5muZFLj3/rMvIAlm7gfXZ80micVVgm root@homelab-woodpecker";
  hostZeroclaw = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIF8hvOMPXx4HOK9/yxL/r8oj1itQIFQDpnk362IwrIfy root@homelab-minimal";
  # Fleet-wide secrets (tailscale auth key, otel push token, fleet enrol
  # secret) go to the humans plus every host that is currently deployed --
  # and only those. A decommissioned VM's host key lives on in its PBS
  # backups and old disk images, so leaving it here keeps every fleet-wide
  # secret decryptable by an artefact nobody is watching. Decommissioned but
  # kept in the tree (hosts/{fleet,harbor,cache}) keep their own per-host
  # secrets below; reviving one is: add its key back here (and to the shared
  # secrets it needs, e.g. axon-gateway-env), `just reencrypt`.
  #
  # hostHermes is back as of the 2026-09 rebuild (docs/plans/hermes-rebuild.md),
  # and was replaced above on 2026-09-24 with the key nixos-anywhere minted
  # during that install. Every hermes secret was re-keyed to it in the same
  # pass; without that, activation fails with "no identity matched any of the
  # recipients".
  #
  # `just reencrypt` is NOT the command for this -- it hardcodes
  # `-i ~/.config/age/keys.txt`, which does not exist on wotan. Use the ssh
  # identity instead, via a passphrase-stripped copy on tmpfs so age (which
  # cannot talk to ssh-agent) does not prompt once per file:
  #   cp ~/.ssh/id_ed25519 /run/user/1000/rekey && ssh-keygen -p -N '' -f /run/user/1000/rekey
  #   cd secrets && agenix -r -i /run/user/1000/rekey && shred -u /run/user/1000/rekey
  # Verify with sha256sum before/after: age uses a fresh ephemeral key per
  # encryption, so an UNCHANGED ciphertext means nothing happened.
  users = [amadeus amadeusWotanAge amadeusMacbookAge amadeusMacbook hostDatabase hostOtel hostDns hostUnifi hostContainers hostMcp hostCa hostForgejo hostJellyfin hostZeroclaw hostDevelopment hostWoodpecker hostHermes];
  # keep-sorted end
in {
  # keep-sorted start

  # The agent user's Forgejo key on development (modules/agent-user.nix): your own collaborator key, pasted in.
  "agent-forgejo-ssh.age".publicKeys = [amadeus amadeusWotanAge amadeusMacbookAge amadeusMacbook hostDevelopment];
  "attic-db-password.age".publicKeys = [amadeus amadeusWotanAge amadeusMacbookAge amadeusMacbook hostDatabase]; # raw password; same value inside attic-db-url.age
  "attic-db-url.age".publicKeys = [amadeus amadeusWotanAge amadeusMacbookAge amadeusMacbook hostCache]; # env-file: ATTIC_SERVER_DATABASE_URL=postgresql://...
  "attic-server-token.age".publicKeys = [amadeus amadeusWotanAge amadeusMacbookAge amadeusMacbook hostCache];
  # hostMcp replaced hostContainers on 2026-09-14 when the gateway moved hosts. Run `just reencrypt` after a recipient change.
  "axon-gateway-env.age".publicKeys = [amadeus amadeusWotanAge amadeusMacbookAge amadeusMacbook hostMcp hostDevelopment hostOtel hostZeroclaw hostHermes];
  "dashboard-env.age".publicKeys = [amadeus amadeusWotanAge amadeusMacbookAge amadeusMacbook hostContainers];
  "development-forgejo-token.age".publicKeys = [amadeus amadeusWotanAge amadeusMacbookAge amadeusMacbook hostDevelopment];
  "development-opencode-zen-key.age".publicKeys = [amadeus amadeusWotanAge amadeusMacbookAge amadeusMacbook hostDevelopment];
  "fleet-enroll-secret.age".publicKeys = users;
  "fleet-mysql-password.age".publicKeys = [amadeus amadeusWotanAge amadeusMacbookAge amadeusMacbook hostFleet];
  "forgejo-db-password.age".publicKeys = [amadeus amadeusWotanAge amadeusMacbookAge amadeusMacbook hostForgejo hostDatabase];
  "futo-notes-db-password.age".publicKeys = [amadeus amadeusWotanAge amadeusMacbookAge amadeusMacbook hostContainers hostDatabase];
  "futo-notes-env.age".publicKeys = [amadeus amadeusWotanAge amadeusMacbookAge amadeusMacbook hostContainers];
  "garage-rpc-secret.age".publicKeys = [amadeus amadeusWotanAge amadeusMacbookAge amadeusMacbook hostCache];
  "grafana-admin-password.age".publicKeys = [amadeus amadeusWotanAge amadeusMacbookAge amadeusMacbook hostOtel]; # break-glass local admin; the UI is OIDC-only
  "grafana-oidc-secret.age".publicKeys = [amadeus amadeusWotanAge amadeusMacbookAge amadeusMacbook hostOtel];
  "grafana-secret-key.age".publicKeys = [amadeus amadeusWotanAge amadeusMacbookAge amadeusMacbook hostOtel];
  "harbor-admin-password.age".publicKeys = [amadeus amadeusWotanAge amadeusMacbookAge amadeusMacbook hostHarbor];
  "harbor-core-secret.age".publicKeys = [amadeus amadeusWotanAge amadeusMacbookAge amadeusMacbook hostHarbor];
  "harbor-db-password.age".publicKeys = [amadeus amadeusWotanAge amadeusMacbookAge amadeusMacbook hostHarbor];
  "harbor-oidc-client-id.age".publicKeys = [amadeus amadeusWotanAge amadeusMacbookAge amadeusMacbook hostHarbor];
  "harbor-oidc-client-secret.age".publicKeys = [amadeus amadeusWotanAge amadeusMacbookAge amadeusMacbook hostHarbor];
  "hermes-agentmail-key.age".publicKeys = [amadeus amadeusWotanAge amadeusMacbookAge amadeusMacbook hostHermes];
  # Per-profile provider credentials. A named Hermes profile resolves its
  # providers only from its OWN .env, so each profile home gets its own file
  # (env-file format: DEEPSEEK_API_KEY=..., optionally OPENCODE_ZEN_API_KEY=...).
  # hosts/hermes/configuration.nix names them; modules/hermes-profiles.nix
  # concatenates each into profiles/<name>/.env at 0600. This separates what
  # each profile USES, not what it could read -- one uid owns all five.
  "hermes-coding-env.age".publicKeys = [amadeus amadeusWotanAge amadeusMacbookAge amadeusMacbook hostHermes];
  # Superseded by hermes-default-env.age (the default profile's own .env).
  # Kept as a recipient entry only while the file still exists in the tree.
  "hermes-deepseek-key.age".publicKeys = [amadeus amadeusWotanAge amadeusMacbookAge amadeusMacbook hostHermes];
  "hermes-default-env.age".publicKeys = [amadeus amadeusWotanAge amadeusMacbookAge amadeusMacbook hostHermes];
  # Re-minted for the 2026-09 rebuild: this now holds the `hermes` Forgejo
  # ACCOUNT's own key, not the retired `hermes-bot` account's.
  "hermes-forgejo-ssh.age".publicKeys = [amadeus amadeusWotanAge amadeusMacbookAge amadeusMacbook hostHermes];
  "hermes-infra-env.age".publicKeys = [amadeus amadeusWotanAge amadeusMacbookAge amadeusMacbook hostHermes];
  "hermes-kb-env.age".publicKeys = [amadeus amadeusWotanAge amadeusMacbookAge amadeusMacbook hostHermes];
  "hermes-opencode-zen-key.age".publicKeys = [amadeus amadeusWotanAge amadeusMacbookAge amadeusMacbook hostHermes];
  "hermes-research-env.age".publicKeys = [amadeus amadeusWotanAge amadeusMacbookAge amadeusMacbook hostHermes];
  "hofvarpnir-db-password.age".publicKeys = [amadeus amadeusWotanAge amadeusMacbookAge amadeusMacbook hostDatabase hostJellyfin];
  "hofvarpnir-env.age".publicKeys = [amadeus amadeusWotanAge amadeusMacbookAge amadeusMacbook hostJellyfin];
  "homeassistant-token.age".publicKeys = [amadeus amadeusWotanAge amadeusMacbookAge amadeusMacbook hostMcp];
  "k3s-server-token.age".publicKeys = [amadeus amadeusWotanAge amadeusMacbookAge amadeusMacbook]; # add hostK3sCntrl1 + `just reencrypt` once k3s-cntrl-1 is installed and its real host key is known
  "moshi-device-id.age".publicKeys = [amadeus amadeusWotanAge amadeusMacbookAge amadeusMacbook hostDevelopment hostZeroclaw hostHermes]; # plain auth token
  "open-webui-env.age".publicKeys = [amadeus amadeusWotanAge amadeusMacbookAge amadeusMacbook hostContainers];
  "otel-push-token.age".publicKeys = users; # bare token; every host's fluent-bit pushes to loki with it (write-only side)
  "otel-query-token.age".publicKeys = [amadeus amadeusWotanAge amadeusMacbookAge amadeusMacbook hostOtel hostMcp]; # bare token; read side of the otel vhosts (prom/loki/tempo/alertmanager MCP servers)
  "pbs-mcp-token.age".publicKeys = [amadeus amadeusWotanAge amadeusMacbookAge amadeusMacbook hostMcp];
  "pg-mcp-appdb-url.age".publicKeys = [amadeus amadeusWotanAge amadeusMacbookAge amadeusMacbook hostMcp];
  "pg-mcp-forgejo-url.age".publicKeys = [amadeus amadeusWotanAge amadeusMacbookAge amadeusMacbook hostMcp];
  "pg-mcp-hofvarpnir-url.age".publicKeys = [amadeus amadeusWotanAge amadeusMacbookAge amadeusMacbook hostMcp];
  "pg-mcp-romm-url.age".publicKeys = [amadeus amadeusWotanAge amadeusMacbookAge amadeusMacbook hostMcp];
  "pg-mcp-terraform-url.age".publicKeys = [amadeus amadeusWotanAge amadeusMacbookAge amadeusMacbook hostMcp];
  "pgadmin-oauth2-secret.age".publicKeys = [amadeus amadeusWotanAge amadeusMacbookAge amadeusMacbook hostDatabase];
  "pgadmin-pwd.age".publicKeys = [amadeus amadeusWotanAge amadeusMacbookAge amadeusMacbook hostDatabase];
  "pgmcp-role-password.age".publicKeys = [amadeus amadeusWotanAge amadeusMacbookAge amadeusMacbook hostDatabase];
  "postgres-superuser-password.age".publicKeys = [amadeus amadeusWotanAge amadeusMacbookAge amadeusMacbook hostDatabase];
  "romm-db-password.age".publicKeys = [amadeus amadeusWotanAge amadeusMacbookAge amadeusMacbook hostContainers hostDatabase];
  "romm-env.age".publicKeys = [amadeus amadeusWotanAge amadeusMacbookAge amadeusMacbook hostContainers];
  "step-ca-password.age".publicKeys = [amadeus amadeusWotanAge amadeusMacbookAge amadeusMacbook hostCa];
  "tailscale-auth-key.age".publicKeys = users;
  "terraform-state-db-password.age".publicKeys = [amadeus amadeusWotanAge amadeusMacbookAge amadeusMacbook hostDatabase];
  "uptime-forge-db-password.age".publicKeys = [amadeus amadeusWotanAge amadeusMacbookAge amadeusMacbook hostContainers];
  "ventara-gateway-env.age".publicKeys = [amadeus amadeusWotanAge amadeusMacbookAge amadeusMacbook hostDevelopment hostHermes];
  "woodpecker-agent-env.age".publicKeys = [amadeus amadeusWotanAge amadeusMacbookAge amadeusMacbook hostWoodpecker]; # WOODPECKER_AGENT_SECRET only; must match the server's byte-for-byte
  "woodpecker-mcp-token.age".publicKeys = [amadeus amadeusWotanAge amadeusMacbookAge amadeusMacbook hostMcp]; # WP_TOKEN for wpmcp-server; a Woodpecker personal access token
  "woodpecker-metrics-token.age".publicKeys = [amadeus amadeusWotanAge amadeusMacbookAge amadeusMacbook hostOtel]; # bare bearer token for prometheus; same value as WOODPECKER_PROMETHEUS_AUTH_TOKEN in woodpecker-server-env.age
  "woodpecker-server-env.age".publicKeys = [amadeus amadeusWotanAge amadeusMacbookAge amadeusMacbook hostWoodpecker]; # WOODPECKER_AGENT_SECRET, WOODPECKER_GRPC_SECRET, WOODPECKER_FORGEJO_CLIENT, WOODPECKER_FORGEJO_SECRET
  # keep-sorted end
}
